### ISSUE TITLE
Use online template from Passport

### ISSUE THREAD

**Issue by Colmea** [mailjet/mailjetBundle#1]
Hi Mailjet team,

I would like to know if there's a way to use this bundle to send online template emails from Mailjet Passport ?
I don't see anything in the doc regarding Passport.

**Comment by Zhivko-Mailjet** [comment]
@Colmea 

Correct me if I'm wrong, but from what I understand you would like to create a template through Passport and send it through the bundle. This is indeed possible, using the ID of the template. In the API call, you add the property 'MJ-TemplateID' => $ID. See here:
https://dev.mailjet.com/guides/?php#use-the-template-in-send-api

Bundle documentation can be found here:
https://mailjet.github.io/mailjetBundle/usage/#retrieve-mailjet-client-object-to-make-custom-mailjet-api-v3-requests

Hope this helps.

**Comment by Nightbr** [comment]
Hi,
@Zhivko-Mailjet yes you're right or you can do it with SwiftMailer and custom headers:

``` php
//Configure Headers
$headers = $message->getHeaders();
// Mailjet header
$headers->addTextHeader('X-MJ-TemplateID', PUT_YOUR_TEMPLATE_ID);

// send email
$this->get('mailer')->send($message);
```

Documentation here:

- <https://mailjet.github.io/mailjetBundle/swiftmailer/>
- <https://dev.mailjet.com/guides/?php#using-a-template>

**Comment by Nightbr** [comment]
@Colmea are these answers resolved your issue?

**Comment by Colmea** [comment]
Yep, thanks for your fast answers !
