### ISSUE TITLE
Send mail in Command

### ISSUE THREAD

**Issue by tibo6** [mailjet/mailjetBundle#10]
Hi,

I want to send an email within a Command, and it doesn't seem to work.
Don't know why.

Did I miss something ?
It works perfectly in a controller.

Thanks.

**Comment by Nightbr** [comment]
we can't help you if you don't provide code lines, errors, logs, ...

**Comment by tibo6** [comment]
I have no error.

Here's my code, nothing special:

```
$em = $this->getContainer()->get('doctrine')->getManager();
$contactsAmount = $em->getRepository('ContactUsBundle:Contact')->getTodaysContactsAmount();
$ordersInformation = $em->getRepository('ShopBundle:SalesOrder')->getOrdersInformation();

$currentDate = new \DateTime('now');

$message = (new \Swift_Message('[Web] Statistiques du '.$currentDate->format('d/m/Y')))
	->setFrom($this->getContainer()->getParameter('mailer_sender'))
	->setTo('xxx@xxx.com')
	->setBody($this->getContainer()->get('templating')->render('AppBundle:Emails:stats.html.twig', array(
		'contactsAmount' => $contactsAmount,
		'ordersInformation' => $ordersInformation
	)), 'text/html');

$emailsSent = $this->getContainer()->get('mailer')->send($message);

$output->writeln($emailsSent.' emails envoyés');
```

$emailsSent returns 0

**Comment by Nightbr** [comment]
verify the symfony env you use when you send your command, also check your spool configuration

**Comment by tibo6** [comment]
When I use this command :
`php bin/console stats:send`
It seems that it is launched in the dev env.
My config for dev env is :
```
swiftmailer:
    disable_delivery: true
```
And $emailsSent returns 1.

But when I use this command :
`php bin/console stats:send --env=prod`
And $emailsSent returns 0.
My config is:
```
swiftmailer:
    transport: mailjet
```
So no spool is configured.

**Comment by Nightbr** [comment]
put some var_dump everywhere, it can be a problem with your payload and Mailjet API reject your request that's why it failed.

**Comment by tibo6** [comment]
OK I removed a `try...catch` in the bundle.
And it gives me an error that I don't have when I send an email in a controller:
```
In CurlFactory.php line 187:
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see: http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

I tried to update my cacert.pem with no result.

**Comment by Nightbr** [comment]
You are on Windows environment? it's a common issue, ask Google for it:

- https://stackoverflow.com/questions/21114371/php-curl-error-code-60
- https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-unable-to-get-local-issuer-certificate
- https://sdujancourt.me/2017/02/28/windows-php-curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/

**Comment by Nightbr** [comment]
But I think we could catch runtime error (other than API error) and throw them in order to get error when there is actual error (like here).
