### ISSUE TITLE
New Tag

### ISSUE THREAD

**Issue by Eliaenor** [mailjet/mailjetBundle#12]
Hello !

Can we have a new tag for the December's changes ? We can't use the bundle since in the last tag MailjetDataCollector::reset() is not defined so we got the error : 

> Error: Class Mailjet\MailjetBundle\DataCollector\MailjetDataCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::reset)

Stack : 
- Symfony 4.0.4
- PHP 7.1

Thank you.

Eliaenor

**Comment by Nightbr** [comment]
ping @Zhivko-Mailjet

**Comment by latanasov** [comment]
Zhivko is no longer part of the team aswell :) . cc @eboisgon  @kachar

**Comment by Seb33300** [comment]
It could be nice if the pending pull request which solve another SF 4 issue could be merged before creating the new tag.

**Comment by Seb33300** [comment]
@Nightbr you already merged pull requests and created new tags.

You cannot do it anymore?

**Comment by Nightbr** [comment]
I'm not in charge anymore.. sorry

**Comment by kachar** [comment]
Added tag https://github.com/mailjet/mailjetBundle/releases/tag/1.0.5
