### ISSUE TITLE
Needs attention on Packages on Packagist.org

### ISSUE THREAD

**Issue by neeckeloo** [mailjet/mailjetBundle#22]
Your package on packagist.org have (Legacy Auto-Update, Needs Attention)

> If you have published packages from GitHub on http://packagist.org please logout/login with GitHub to let us upgrade the auto-update hooks and remove the deprecated GitHub service hooks. See “GitHub Hook” on https://packagist.org/about#how-to-update-packages for more details.

> Note that things will keep working fine as-is until January 2019 so no rush doing this but do it when you get a chance to make sure your packages keep updating smoothly.

Source about how-to-do: https://twitter.com/packagist/status/1037035587453235201

**Comment by mskochev** [comment]
Hi, problem solved and packagist is updated.
