### ISSUE TITLE
Error in mailjet-bundle/src/Resources/config/services.yml line 76

### ISSUE THREAD

**Issue by blaisesampleo** [mailjet/mailjetBundle#30]
Hi,

There are some extra unneeded space chars at the end of  line 76
in mailjet-bundle/src/Resources/config/services.yml

with latest symfony 4.4.xx updates, this generates an error
on bin/console assets:install

those extra chars generate an exception in bin/console

**Comment by DylanGD** [comment]
Yes some back spaces need to be removed, please fix it

**Comment by Hraph** [comment]
In the meanwhile, I had to run this command in my Dockerfile:
`sed -i "76s/.*/            - '@mailjet.client'/" vendor/mailjet/mailjet-bundle/src/Resources/config/services.yml`

**Comment by webaaz** [comment]
I confirm the bug and the fix

**Comment by uavn** [comment]
@blaisesampleo @DylanGD @Hraph @webaaz

fix is now merged to master
