### ISSUE TITLE
MailjetClient is not compatible with Mailjet\Client

### ISSUE THREAD

**Issue by anthony-launay** [mailjet/mailjetBundle#33]
MailjetClient is not compatible with Mailjet\Client

`
Fatal error: Declaration of Mailjet\MailjetBundle\Client\MailjetClient::post($resource, array $args = Array, array $options = Array) must be compatible with Mailjet\Client::post(array $resource, array $args = Array, array $options = Array): Mailjet\Response in /var/www/web/vendor/mailjet/mailjet-bundle/src/Client/MailjetClient.php on line 19
`

https://github.com/mailjet/mailjetBundle/blob/master/src/Client/MailjetClient.php
https://github.com/mailjet/mailjet-apiv3-php/blob/v1.5.5/src/Mailjet/Client.php

**Comment by anthony-launay** [comment]
https://github.com/mailjet/mailjetBundle/pull/34

**Comment by floviolleau** [comment]
Hi,

Seems to be merged.

I think we can close it
