### ISSUE TITLE
Compatibility with Symfony Flex

### ISSUE THREAD

**Issue by Nightbr** [mailjet/mailjetBundle#7]
I think this could be a nice feature to this bundle and can set Mailjet as the first Mail service compatible with Symfony Flex recipe.

https://github.com/symfony/recipes-contrib

**Comment by Taluu** [comment]
Would be even better IMO if a support for "MAILER_URL" type configuration (e.g mailjet://apikey:apisecret@api.mailjet.com/v3` or something along those lines ?)

**Comment by Nightbr** [comment]
@Taluu wow it could be really great but is this possible through composer?

**Comment by Taluu** [comment]
Well that would be up to the dependency injection extension I think, as it is done on swiftmailer's bundle and its transport factory : https://github.com/symfony/swiftmailer-bundle/blob/master/DependencyInjection/SwiftmailerTransportFactory.php#L85

So basically, we could build a `Mailjet\Client` (through a `Mailjet\ClientUri` or something ? extending the original client), which could then be used by the swiftmailer transport

**Comment by lbassin** [comment]
FYI i made a PR to resolve this issue, it will be merged soon 
The PR add a recipe for current configuration, it doesn't include MAILER_URL

**Comment by lbassin** [comment]
Mailjet recipe is now available :confetti_ball: 
I think we can close this issue and open a new one to talk about the url
