### ISSUE TITLE
Symfony 3.4 : User Deprecated

### ISSUE THREAD

**Issue by tibo6** [mailjet/mailjetBundle#8]
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since version 3.4 and will be unsupported in 4.0 for class "Mailjet\MailjetBundle\DataCollector\MailjetDataCollector".

**Comment by Nightbr** [comment]
Seems to be an easy pick, just create a reset() method in MailjetDataCollector with `$this->data = array();` to reset the data array.

You could be great if you can create a PR for this.

**Comment by tibo6** [comment]
Done.

**Comment by Nightbr** [comment]
merged
